<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<link rel="shortcut icon" type="image/png" href="favicon.png">';
echo '<title>Della's Website!</title>';
echo '<style>';
echo 'html {background-image: url("shibebackground.jpg"); background-color: black;}';
echo 'body {max-width: 650px; margin: auto; margin-top: 12px; margin-bottom: 12px; font-family: 'Mona'; src: url('data/Mona.ttf');}';
echo 'main {padding: 8px; padding-left: 12px; padding-right: 12px; background-image: url("blueskye.jpg");}';
echo 'h1,h2,h3 {font-family: 'Palatino Linotype'; src: url('data/pala.ttf');}';
echo 'h1 {text-shadow: 2px 2px #ffacac; color: #ffbebe; font-size: 26px; text-align: center;}';
echo 'h2 {text-shadow: 2px 2px #d4a362; font-size: 30px; color: #F8BE71; text-align: center;}';
echo 'h3 {border-bottom: 1px double rgb(0, 0, 0); padding: 4px}';
echo 'h4 {border: 1px solid black; padding: 2px;background-color: white; box-shadow: 5px 5px grey}';
echo 'a {text-decoration: none}';
echo '.title {background-image: url("pinktexture.png"); box-shadow: 5px 5px #ffe7e7;}';
echo '.text {border: 1px solid black; padding: 2px; background-color: white; box-shadow: 5px 5px grey}';
echo '.center {text-align: center;}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '<main>';
echo '<h1>.*＊✿ Welcome to... ✿＊*.</h1>';
echo '<div class=title>';
echo '<h2>✧༺♥༻ Della's Website! ༺♥༻✧</h2>';
echo '</div>';
echo '<div class=center>';
echo '<img title="Shibe." src="shibe1.png" style="width:120px; height:120px; border:6px solid white; box-shadow: 5px 5px grey">';
echo '<h4 style="margin-left: auto;margin-right: auto; width: 85px">About me:</h4>';
echo '</div>';
echo '<div class=text>';
echo '<p>⠀★ Hi! I'm Della, welcome to my website! I'm a digital artist, YouTuber, and proud cat owner!</p>';
echo '<h3>୨୧ Things I enjoy: ୨୧</h3>';
echo '<p>⠀★ Cats and dogs.</p>';
echo '<p>⠀★ Making artwork.</p>';
echo '<p>⠀★ Cute clothes.</p>';
echo '<p>⠀★ Making YouTube videos!</p>';
echo '</div>';
echo '<div class=center>';
echo '<h4>‧⁺˚*･༓ ✿';
echo '<a style="color:#aabaff" href="https://discord.gg/qb5z3Y2Aca ">Discord </a>✿';
echo '<a style="color:#aabaff" href="https://www.youtube.com/channel/UCtMA2dgxu0G_waNWWBx69Dw">YouTube </a>✿';
echo '<a style="color:#aabaff" href="https://www.roblox.com/users/877804212/profile">Roblox </a>✿  ༓･*˚⁺‧';
echo '</h4>';
echo '</div>';
echo '</main>';
echo '</body>';
echo '</html>';
echo '';
?>
